UPDATE tools SET command_template = 'aircrack-ng {target} {wordlist} {bssid}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'aircrack-ng' AND is_active = TRUE;
UPDATE tools SET command_template = 'amass enum -passive -d {domain}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'amass' AND is_active = TRUE;
UPDATE tools SET command_template = 'assetfinder {domain} {subs_only}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'assetfinder' AND is_active = TRUE;
UPDATE tools SET command_template = 'bettercap -iface {target} {eval_script}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'bettercap' AND is_active = TRUE;
UPDATE tools SET command_template = 'binwalk {target} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'binwalk' AND is_active = TRUE;
UPDATE tools SET command_template = 'bloodhound-python -u {username} -p {password} -d {domain} -c {collection}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'bloodhound-python' AND is_active = TRUE;
UPDATE tools SET command_template = 'bulk_extractor {target} {output}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'bulk_extractor' AND is_active = TRUE;
UPDATE tools SET command_template = 'cewl {url} {depth} {min_length} {output}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'cewl' AND is_active = TRUE;
UPDATE tools SET command_template = 'chisel client {target} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'chisel' AND is_active = TRUE;
UPDATE tools SET command_template = 'chntpw {target} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'chntpw' AND is_active = TRUE;
UPDATE tools SET command_template = 'netexec smb {target} {creds} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'crackmapexec' AND is_active = TRUE;
UPDATE tools SET command_template = 'dirsearch -u {url} {extensions} {threads}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'dirsearch' AND is_active = TRUE;
UPDATE tools SET command_template = 'dnsenum {domain} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'dnsenum' AND is_active = TRUE;
UPDATE tools SET command_template = 'dnsrecon -d {domain} {type}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'dnsrecon' AND is_active = TRUE;
UPDATE tools SET command_template = 'dsniff -i {target} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'dsniff' AND is_active = TRUE;
UPDATE tools SET command_template = 'enum4linux {target} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'enum4linux' AND is_active = TRUE;
UPDATE tools SET command_template = 'enum4linux-ng {target} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'enum4linux-ng' AND is_active = TRUE;
UPDATE tools SET command_template = 'ettercap -T -i {target} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'ettercap' AND is_active = TRUE;
UPDATE tools SET command_template = 'evil-winrm -i {target} -u {username} -p {password} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'evil-winrm' AND is_active = TRUE;
UPDATE tools SET command_template = 'fcrackzip {target} {wordlist}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'fcrackzip' AND is_active = TRUE;
UPDATE tools SET command_template = 'feroxbuster -u {url} {wordlist} {depth} {threads}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'feroxbuster' AND is_active = TRUE;
UPDATE tools SET command_template = 'ffuf -u {url} {wordlist} {matches}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'ffuf' AND is_active = TRUE;
UPDATE tools SET command_template = 'fierce --domain {domain} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'fierce' AND is_active = TRUE;
UPDATE tools SET command_template = 'foremost -i {target} {output}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'foremost' AND is_active = TRUE;
UPDATE tools SET command_template = 'fping {target} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'fping' AND is_active = TRUE;
UPDATE tools SET command_template = 'gospider -s {url} {depth} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'gospider' AND is_active = TRUE;
UPDATE tools SET command_template = 'hashcat -m {mode} -a {attack_mode} {target} {wordlist} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'hashcat' AND is_active = TRUE;
UPDATE tools SET command_template = 'hashid {target} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'hashid' AND is_active = TRUE;
UPDATE tools SET command_template = 'hping3 {target} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'hping3' AND is_active = TRUE;
UPDATE tools SET command_template = 'joomscan --url {url} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'joomscan' AND is_active = TRUE;
UPDATE tools SET command_template = 'kismet -c {target} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'kismet' AND is_active = TRUE;
UPDATE tools SET command_template = 'macchanger {target} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'macchanger' AND is_active = TRUE;
UPDATE tools SET command_template = 'masscan {target} {ports} {rate}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'masscan' AND is_active = TRUE;
UPDATE tools SET command_template = 'mitmproxy --listen-port {target} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'mitmproxy' AND is_active = TRUE;
UPDATE tools SET command_template = 'msfvenom -p {target} LHOST={lhost} LPORT={lport} -f {format} -o {output} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'msfvenom' AND is_active = TRUE;
UPDATE tools SET command_template = 'ncat {target} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'ncat' AND is_active = TRUE;
UPDATE tools SET command_template = 'ncrack {target} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'ncrack' AND is_active = TRUE;
UPDATE tools SET command_template = 'netdiscover -r {target} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'netdiscover' AND is_active = TRUE;
UPDATE tools SET command_template = 'netexec smb {target} {creds} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'netexec' AND is_active = TRUE;
UPDATE tools SET command_template = 'nikto -h {target} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'nikto' AND is_active = TRUE;
UPDATE tools SET command_template = 'nmap {target} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'nmap' AND is_active = TRUE;
UPDATE tools SET command_template = 'nuclei -u {url} {severity} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'nuclei' AND is_active = TRUE;
UPDATE tools SET command_template = 'photorec {output} {target}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'photorec' AND is_active = TRUE;
UPDATE tools SET command_template = 'pixiewps {target} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'pixiewps' AND is_active = TRUE;
UPDATE tools SET command_template = 'radare2 {target} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'radare2' AND is_active = TRUE;
UPDATE tools SET command_template = 'reaver -i {target} -b {bssid} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'reaver' AND is_active = TRUE;
UPDATE tools SET command_template = 'regripper -r {target} -p {plugin} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'regripper' AND is_active = TRUE;
UPDATE tools SET command_template = 'responder -I {target} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'responder' AND is_active = TRUE;
UPDATE tools SET command_template = 'rizin {target} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'rizin' AND is_active = TRUE;
UPDATE tools SET command_template = 'samdump2 {target} {system_hive}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'samdump2' AND is_active = TRUE;
UPDATE tools SET command_template = 'searchsploit {target} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'searchsploit' AND is_active = TRUE;
UPDATE tools SET command_template = 'smbmap -H {target} {creds} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'smbmap' AND is_active = TRUE;
UPDATE tools SET command_template = 'socat {target} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'socat' AND is_active = TRUE;
UPDATE tools SET command_template = 'sshuttle -r {target} {subnet} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'sshuttle' AND is_active = TRUE;
UPDATE tools SET command_template = 'ssdeep {target} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'ssdeep' AND is_active = TRUE;
UPDATE tools SET command_template = 'subfinder -d {domain} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'subfinder' AND is_active = TRUE;
UPDATE tools SET command_template = 'tcpdump -i {target} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'tcpdump' AND is_active = TRUE;
UPDATE tools SET command_template = 'tcpreplay -i {target} {pcap}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'tcpreplay' AND is_active = TRUE;
UPDATE tools SET command_template = 'testdisk {target} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'testdisk' AND is_active = TRUE;
UPDATE tools SET command_template = 'theHarvester -d {domain} -b {source} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'theHarvester' AND is_active = TRUE;
UPDATE tools SET command_template = 'unicornscan {target} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'unicornscan' AND is_active = TRUE;
UPDATE tools SET command_template = 'wafw00f {target} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'wafw00f' AND is_active = TRUE;
UPDATE tools SET command_template = 'wapiti --url {url} {module} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'wapiti' AND is_active = TRUE;
UPDATE tools SET command_template = 'whatweb {url} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'whatweb' AND is_active = TRUE;
UPDATE tools SET command_template = 'wifite -i {target} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'wifite' AND is_active = TRUE;
UPDATE tools SET command_template = 'wifiphisher -aI {target} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'wifiphisher' AND is_active = TRUE;
UPDATE tools SET command_template = 'wpscan --url {url} {options}', parameters = '{"danger_level": "low", "target_types": []}' WHERE name = 'wpscan' AND is_active = TRUE;
