"use client";

import { useTranslations } from "next-intl";
import RevealOnScroll from "@/components/animations/RevealOnScroll";
import ThreatPulse from "@/components/three/ThreatPulse";

const sections = [
  { title: "Acceptance of Terms", content: "By accessing or using CyberSec Pro, you agree to be bound by these Terms of Service. If you do not agree, do not use our services." },
  { title: "Authorized Use Only", content: "You may only use CyberSec Pro for authorized security testing. You must have explicit written permission from the owner of any system you scan. Unauthorized scanning is a violation of these terms and may be illegal." },
  { title: "Account Responsibilities", content: "You are responsible for maintaining the security of your account credentials. You must not share your account or API keys. You are liable for all activities performed under your account." },
  { title: "Subscription & Payments", content: "Paid plans are billed monthly or annually. Prices are in EUR and exclude applicable taxes. Refunds are available within 14 days of purchase if no scans have been executed." },
  { title: "Service Availability", content: "We target 99.9% uptime but do not guarantee uninterrupted service. Scheduled maintenance windows will be communicated in advance. Enterprise plans include SLA guarantees." },
  { title: "Intellectual Property", content: "All platform code, design, and documentation are owned by CyberSec Pro. Scan results and reports generated by you belong to you. Tool integrations are subject to their respective licenses." },
  { title: "Limitation of Liability", content: "CyberSec Pro is provided 'as is'. We are not liable for damages arising from your use of the platform, including but not limited to data loss, service interruptions, or consequences of unauthorized scanning." },
  { title: "Termination", content: "We may suspend or terminate your account for violation of these terms. Upon termination, your data will be retained for 30 days before deletion." },
];

export default function TermsPage() {
  const t = useTranslations("terms");

  return (
    <>
      <ThreatPulse />
      <section className="mx-auto max-w-3xl px-6 pb-28 pt-32">
      <RevealOnScroll>
        <h1 className="text-4xl font-extrabold md:text-5xl">{t("title")}</h1>
        <p className="mt-2 text-sm text-white/40">{t("lastUpdated")}</p>
      </RevealOnScroll>
      <div className="mt-12 flex flex-col gap-8">
        {sections.map((s) => (
          <RevealOnScroll key={s.title}>
            <h2 className="mb-2 text-lg font-bold text-white">{s.title}</h2>
            <p className="text-sm leading-relaxed text-white/50">{s.content}</p>
          </RevealOnScroll>
        ))}
      </div>
    </section>
    </>
  );
}
