// AUTO-GENERATED — modern security tools catalog (~225 entries).
// Complement to hackingtool_seed.rs. Same Entry shape.
//
// To regenerate: python3 /tmp/gen_modern.py > rust-backend/src/services/hackingtool_seed_modern.rs

use serde_json::{json, Value};
use sqlx::PgPool;
use super::hackingtool_seed::{
    p_target, p_url, p_domain, p_file, p_apk, p_none,
};

type Entry = (
    &'static str, &'static str, &'static str, &'static str, &'static str,
    &'static str, &'static str, &'static str, &'static str, &'static [&'static str], fn() -> Value,
);

fn catalog_modern() -> Vec<Entry> {
    vec![
        ("ht_cloudsploit", "cloudsploit", "cloud_security", "cspm",
            "Open-source cloud security posture management for AWS/Azure/GCP/OCI.",
            "npm install -g cloudsploit",
            "cloudsploit scan --console table",
            "https://github.com/aquasecurity/cloudsploit",
            "medium", &["cloud"], p_none),
        ("ht_cloudfox", "cloudfox", "cloud_security", "cloud_recon",
            "Find exploitable attack paths in cloud infrastructure.",
            "go install github.com/BishopFox/cloudfox@latest",
            "cloudfox aws all",
            "https://github.com/BishopFox/cloudfox",
            "medium", &["cloud"], p_none),
        ("ht_cloudbrute", "cloudbrute", "cloud_security", "cloud_recon",
            "Find a target company's public infrastructure on multiple cloud providers.",
            "go install github.com/0xsha/cloudbrute@latest",
            "cloudbrute -d {domain} -k {domain}",
            "https://github.com/0xsha/CloudBrute",
            "low", &["domain"], p_domain),
        ("ht_s3scanner", "s3scanner", "cloud_security", "aws_offensive",
            "Scan for misconfigured S3 buckets across regions.",
            "pipx install s3scanner",
            "s3scanner scan --bucket {target}",
            "https://github.com/sa7mon/S3Scanner",
            "low", &["target"], p_target),
        ("ht_gcpbucketbrute", "gcpbucketbrute", "cloud_security", "gcp_offensive",
            "Brute-force GCS bucket names and check permissions.",
            "git clone https://github.com/RhinoSecurityLabs/GCPBucketBrute && pip3 install -r GCPBucketBrute/requirements.txt",
            "python3 GCPBucketBrute/gcpbucketbrute.py -k {target} -u",
            "https://github.com/RhinoSecurityLabs/GCPBucketBrute",
            "low", &["target"], p_target),
        ("ht_cloudmapper", "cloudmapper", "cloud_security", "aws_visualize",
            "Help analyze AWS environments with visualizations.",
            "git clone https://github.com/duo-labs/cloudmapper && cd cloudmapper && pipenv install",
            "python3 cloudmapper.py audit",
            "https://github.com/duo-labs/cloudmapper",
            "low", &["cloud"], p_none),
        ("ht_cartography", "cartography", "cloud_security", "asset_graph",
            "Consolidate infrastructure assets and relationships into a Neo4j graph.",
            "pip3 install cartography",
            "cartography --neo4j-uri bolt://localhost:7687",
            "https://github.com/lyft/cartography",
            "low", &["cloud"], p_none),
        ("ht_aws_pwn", "aws_pwn", "cloud_security", "aws_offensive",
            "Collection of AWS penetration testing scripts.",
            "git clone https://github.com/dagrz/aws_pwn",
            "python3 aws_pwn/{flags}",
            "https://github.com/dagrz/aws_pwn",
            "high", &["cloud"], p_none),
        ("ht_peirates", "peirates", "cloud_security", "k8s_offensive",
            "Kubernetes penetration testing tool.",
            "git clone https://github.com/inguardians/peirates && cd peirates && go build",
            "./peirates",
            "https://github.com/inguardians/peirates",
            "high", &["k8s"], p_none),
        ("ht_weirdaal", "weirdaal", "cloud_security", "aws_offensive",
            "AWS attack library for offensive testing.",
            "git clone https://github.com/carnal0wnage/weirdAAL",
            "python3 weirdAAL/weirdAAL.py -m {flags}",
            "https://github.com/carnal0wnage/weirdAAL",
            "high", &["cloud"], p_none),
        ("ht_endgame", "endgame", "cloud_security", "aws_share",
            "Identify and exploit AWS resource shares.",
            "pipx install endgame",
            "endgame expose --service all",
            "https://github.com/DavidDikker/endgame",
            "medium", &["cloud"], p_none),
        ("ht_checkov", "checkov", "cloud_security", "iac_scan",
            "Static code analysis for Terraform/CFN/K8s/Docker.",
            "pipx install checkov",
            "checkov -d {file}",
            "https://github.com/bridgecrewio/checkov",
            "low", &["file"], p_file),
        ("ht_tfsec", "tfsec", "cloud_security", "iac_scan",
            "Security scanner for Terraform code.",
            "brew install tfsec || curl -L https://github.com/aquasecurity/tfsec/releases/latest/download/tfsec-linux-amd64 -o /usr/local/bin/tfsec",
            "tfsec {file}",
            "https://github.com/aquasecurity/tfsec",
            "low", &["file"], p_file),
        ("ht_terrascan", "terrascan", "cloud_security", "iac_scan",
            "Detect compliance and security violations in IaC.",
            "curl -L https://github.com/tenable/terrascan/releases/latest/download/terrascan_Linux_x86_64.tar.gz | tar xz -C /usr/local/bin terrascan",
            "terrascan scan -d {file}",
            "https://github.com/tenable/terrascan",
            "low", &["file"], p_file),
        ("ht_kics", "kics", "cloud_security", "iac_scan",
            "Find security vulnerabilities, compliance issues and infra misconfigs.",
            "docker pull checkmarx/kics",
            "docker run -v $PWD:/path checkmarx/kics scan -p {file}",
            "https://github.com/Checkmarx/kics",
            "low", &["file"], p_file),
        ("ht_regula", "regula", "cloud_security", "iac_scan",
            "Tool that evaluates IaC for security and compliance.",
            "brew install fugue/regula/regula",
            "regula run {file}",
            "https://github.com/fugue/regula",
            "low", &["file"], p_file),
        ("ht_cloudsplaining", "cloudsplaining", "cloud_security", "iam_audit",
            "AWS IAM Security Assessment tool.",
            "pipx install cloudsplaining",
            "cloudsplaining download && cloudsplaining scan",
            "https://github.com/salesforce/cloudsplaining",
            "low", &["cloud"], p_none),
        ("ht_parliament", "parliament", "cloud_security", "iam_audit",
            "AWS IAM linting library.",
            "pipx install parliament",
            "parliament --file {file}",
            "https://github.com/duo-labs/parliament",
            "low", &["file"], p_file),
        ("ht_iamspy", "iamspy", "cloud_security", "iam_audit",
            "Visualize AWS IAM permissions.",
            "pip3 install iamspy",
            "iamspy report",
            "https://github.com/WithSecureLabs/IAMSpy",
            "low", &["cloud"], p_none),
        ("ht_principalmapper", "principalmapper", "cloud_security", "iam_audit",
            "AWS IAM Authorization Engine.",
            "pipx install principalmapper",
            "pmapper graph create && pmapper visualize",
            "https://github.com/nccgroup/PMapper",
            "low", &["cloud"], p_none),
        ("ht_cred_scanner", "cloudgrappler", "cloud_security", "threat_hunt",
            "Identify IoCs in cloud audit logs (AWS CloudTrail).",
            "pipx install cloudgrappler",
            "cloudgrappler --file {file}",
            "https://github.com/permiso-io-tools/cloudgrappler",
            "low", &["file"], p_file),
        ("ht_grype", "grype", "container_security", "vuln_scan",
            "Container/file system vulnerability scanner.",
            "curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin",
            "grype {target}",
            "https://github.com/anchore/grype",
            "low", &["image"], p_target),
        ("ht_syft", "syft", "container_security", "sbom",
            "Generate SBOM from container images and filesystems.",
            "curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin",
            "syft {target}",
            "https://github.com/anchore/syft",
            "low", &["image"], p_target),
        ("ht_docker_bench", "docker_bench", "container_security", "cis_benchmark",
            "Docker CIS benchmark security audits.",
            "git clone https://github.com/docker/docker-bench-security",
            "sudo bash docker-bench-security/docker-bench-security.sh",
            "https://github.com/docker/docker-bench-security",
            "low", &["host"], p_none),
        ("ht_dockle", "dockle", "container_security", "image_lint",
            "Container image linter for security.",
            "curl -L https://github.com/goodwithtech/dockle/releases/latest/download/dockle_Linux-64bit.tar.gz | tar xz -C /usr/local/bin dockle",
            "dockle {target}",
            "https://github.com/goodwithtech/dockle",
            "low", &["image"], p_target),
        ("ht_falco", "falco", "container_security", "runtime",
            "Cloud-native runtime threat detection.",
            "curl -s https://falco.org/repo/falcosecurity-packages.asc | sudo apt-key add - && sudo apt install -y falco",
            "sudo falco -r {file}",
            "https://github.com/falcosecurity/falco",
            "low", &["host"], p_file),
        ("ht_clair", "clair", "container_security", "vuln_scan",
            "Vulnerability static analysis for containers.",
            "docker pull quay.io/projectquay/clair:latest",
            "docker run quay.io/projectquay/clair scan {target}",
            "https://github.com/quay/clair",
            "low", &["image"], p_target),
        ("ht_anchore_engine", "anchore_engine", "container_security", "vuln_scan",
            "Inspect, analyze and apply policy to container images.",
            "docker run -d -p 8228:8228 anchore/anchore-engine",
            "anchore-cli image add {target}",
            "https://github.com/anchore/anchore-engine",
            "low", &["image"], p_target),
        ("ht_snyk", "snyk", "container_security", "vuln_scan",
            "Find and fix vulnerabilities in dependencies and containers.",
            "npm install -g snyk",
            "snyk container test {target}",
            "https://github.com/snyk/snyk",
            "low", &["image"], p_target),
        ("ht_hadolint", "hadolint", "container_security", "dockerfile_lint",
            "Dockerfile linter for best practices and security.",
            "curl -L https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64 -o /usr/local/bin/hadolint && chmod +x /usr/local/bin/hadolint",
            "hadolint {file}",
            "https://github.com/hadolint/hadolint",
            "low", &["file"], p_file),
        ("ht_dive", "dive", "container_security", "image_inspect",
            "Tool for exploring layers in a docker image.",
            "curl -L https://github.com/wagoodman/dive/releases/latest/download/dive_linux_amd64.tar.gz | tar xz -C /usr/local/bin dive",
            "dive {target}",
            "https://github.com/wagoodman/dive",
            "low", &["image"], p_target),
        ("ht_container_diff", "container_diff", "container_security", "image_inspect",
            "Diff and analyze container images.",
            "curl -LO https://storage.googleapis.com/container-diff/latest/container-diff-linux-amd64 && chmod +x container-diff-linux-amd64 && sudo mv container-diff-linux-amd64 /usr/local/bin/container-diff",
            "container-diff analyze {target}",
            "https://github.com/GoogleContainerTools/container-diff",
            "low", &["image"], p_target),
        ("ht_kube_bench", "kube_bench", "kubernetes_security", "cis_benchmark",
            "Checks K8s clusters against CIS Kubernetes benchmark.",
            "curl -L https://github.com/aquasecurity/kube-bench/releases/latest/download/kube-bench_linux_amd64.tar.gz | tar xz -C /usr/local/bin kube-bench",
            "kube-bench",
            "https://github.com/aquasecurity/kube-bench",
            "low", &["k8s"], p_none),
        ("ht_kube_hunter", "kube_hunter", "kubernetes_security", "vuln_scan",
            "Hunt for security weaknesses in K8s clusters.",
            "pipx install kube-hunter",
            "kube-hunter --remote {target}",
            "https://github.com/aquasecurity/kube-hunter",
            "medium", &["k8s"], p_target),
        ("ht_kubeaudit", "kubeaudit", "kubernetes_security", "config_audit",
            "Helps audit K8s clusters for security issues.",
            "curl -L https://github.com/Shopify/kubeaudit/releases/latest/download/kubeaudit_linux_amd64.tar.gz | tar xz -C /usr/local/bin kubeaudit",
            "kubeaudit all",
            "https://github.com/Shopify/kubeaudit",
            "low", &["k8s"], p_none),
        ("ht_kubescape", "kubescape", "kubernetes_security", "posture",
            "K8s security platform: misconfig, vuln, compliance.",
            "curl -s https://raw.githubusercontent.com/kubescape/kubescape/master/install.sh | bash",
            "kubescape scan",
            "https://github.com/kubescape/kubescape",
            "low", &["k8s"], p_none),
        ("ht_kubesec", "kubesec", "kubernetes_security", "manifest_scan",
            "Security risk analysis for K8s resources.",
            "curl -L https://github.com/controlplaneio/kubesec/releases/latest/download/kubesec_linux_amd64.tar.gz | tar xz -C /usr/local/bin kubesec",
            "kubesec scan {file}",
            "https://github.com/controlplaneio/kubesec",
            "low", &["file"], p_file),
        ("ht_polaris", "polaris", "kubernetes_security", "best_practices",
            "Validation of best practices for K8s deployments.",
            "curl -L https://github.com/FairwindsOps/polaris/releases/latest/download/polaris_linux_amd64.tar.gz | tar xz -C /usr/local/bin polaris",
            "polaris audit --format pretty",
            "https://github.com/FairwindsOps/polaris",
            "low", &["k8s"], p_none),
        ("ht_kubesploit", "kubesploit", "kubernetes_security", "offensive",
            "Cross-platform post-exploitation HTTP/2 C2 server for K8s.",
            "git clone https://github.com/CyberArk/kubesploit && cd kubesploit && go build cmd/server/main.go",
            "./kubesploit",
            "https://github.com/cyberark/kubesploit",
            "high", &["k8s"], p_none),
        ("ht_botkube", "botkube", "kubernetes_security", "monitor",
            "Monitoring and alerting for K8s.",
            "helm repo add botkube https://charts.botkube.io && helm install botkube botkube/botkube",
            "botkube",
            "https://github.com/kubeshop/botkube",
            "low", &["k8s"], p_none),
        ("ht_k_rail", "k-rail", "kubernetes_security", "admission",
            "K8s security workloads policy enforcement.",
            "helm repo add k-rail https://cruise-automation.github.io/k-rail/charts && helm install k-rail k-rail/k-rail",
            "k-rail",
            "https://github.com/cruise-automation/k-rail",
            "low", &["k8s"], p_none),
        ("ht_kubelinter", "kubelinter", "kubernetes_security", "manifest_scan",
            "Static analysis tool for K8s YAML files.",
            "go install golang.stackrox.io/kube-linter/cmd/kube-linter@latest",
            "kube-linter lint {file}",
            "https://github.com/stackrox/kube-linter",
            "low", &["file"], p_file),
        ("ht_starboard", "starboard", "kubernetes_security", "operator",
            "K8s native security toolkit (vuln/risk operator).",
            "curl -L https://github.com/aquasecurity/starboard/releases/latest/download/starboard_linux_x86_64.tar.gz | tar xz -C /usr/local/bin starboard",
            "starboard install",
            "https://github.com/aquasecurity/starboard",
            "low", &["k8s"], p_none),
        ("ht_kdigger", "kdigger", "kubernetes_security", "context_discover",
            "Context discovery tool for K8s pen testing.",
            "go install github.com/quarkslab/kdigger/cmd/kdigger@latest",
            "kdigger dig all",
            "https://github.com/quarkslab/kdigger",
            "medium", &["k8s"], p_none),
        ("ht_kubeeye", "kubeeye", "kubernetes_security", "config_audit",
            "Inspection tool for K8s to find various problems.",
            "curl -L https://github.com/kubesphere/kubeeye/releases/latest/download/ke-linux.tar.gz | tar xz -C /usr/local/bin ke",
            "ke audit",
            "https://github.com/kubesphere/kubeeye",
            "low", &["k8s"], p_none),
        ("ht_semgrep", "semgrep", "supply_chain", "sast",
            "Lightweight static analysis for many languages.",
            "pipx install semgrep",
            "semgrep --config auto {file}",
            "https://github.com/semgrep/semgrep",
            "low", &["file"], p_file),
        ("ht_codeql", "codeql", "supply_chain", "sast",
            "Semantic code analysis engine.",
            "curl -L https://github.com/github/codeql-cli-binaries/releases/latest/download/codeql-linux64.zip -o /tmp/codeql.zip && unzip /tmp/codeql.zip -d /opt && ln -s /opt/codeql/codeql /usr/local/bin/codeql",
            "codeql database analyze {file}",
            "https://github.com/github/codeql-cli-binaries",
            "low", &["file"], p_file),
        ("ht_bandit", "bandit", "supply_chain", "sast_python",
            "Find common security issues in Python code.",
            "pipx install bandit",
            "bandit -r {file}",
            "https://github.com/PyCQA/bandit",
            "low", &["file"], p_file),
        ("ht_safety", "safety", "supply_chain", "dep_scan",
            "Check Python dependencies for known security vulnerabilities.",
            "pipx install safety",
            "safety check -r {file}",
            "https://github.com/pyupio/safety",
            "low", &["file"], p_file),
        ("ht_npm_audit", "npm_audit", "supply_chain", "dep_scan",
            "Check npm dependencies for vulnerabilities.",
            "npm install -g npm",
            "npm audit --audit-level=moderate",
            "https://docs.npmjs.com/cli/v10/commands/npm-audit",
            "low", &["file"], p_none),
        ("ht_osv_scanner", "osv_scanner", "supply_chain", "dep_scan",
            "Vulnerability scanner using the OSV database.",
            "go install github.com/google/osv-scanner/cmd/osv-scanner@latest",
            "osv-scanner --recursive {file}",
            "https://github.com/google/osv-scanner",
            "low", &["file"], p_file),
        ("ht_cargo_audit", "cargo_audit", "supply_chain", "dep_scan_rust",
            "Audit Cargo.lock files for crates with security vulnerabilities.",
            "cargo install cargo-audit",
            "cargo audit",
            "https://github.com/rustsec/rustsec",
            "low", &["file"], p_none),
        ("ht_govulncheck", "govulncheck", "supply_chain", "dep_scan_go",
            "Reports known vulnerabilities affecting Go code.",
            "go install golang.org/x/vuln/cmd/govulncheck@latest",
            "govulncheck ./...",
            "https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck",
            "low", &["file"], p_none),
        ("ht_retire_js", "retire_js", "supply_chain", "dep_scan_js",
            "Scanner for JavaScript libraries with known vulnerabilities.",
            "npm install -g retire",
            "retire --path {file}",
            "https://github.com/RetireJS/retire.js",
            "low", &["file"], p_file),
        ("ht_depcheck", "depcheck", "supply_chain", "dep_audit",
            "Check OWASP for vulnerable dependencies.",
            "curl -L https://github.com/jeremylong/DependencyCheck/releases/latest/download/dependency-check-9.0.7-release.zip -o /tmp/dc.zip && unzip /tmp/dc.zip -d /opt",
            "/opt/dependency-check/bin/dependency-check.sh --scan {file}",
            "https://github.com/jeremylong/DependencyCheck",
            "low", &["file"], p_file),
        ("ht_snyk_code", "snyk_code", "supply_chain", "sast",
            "Snyk SAST and SCA combined.",
            "npm install -g snyk",
            "snyk code test {file}",
            "https://snyk.io/product/snyk-code/",
            "low", &["file"], p_file),
        ("ht_sigstore_cosign", "cosign", "supply_chain", "signing",
            "Container signing, verification and storage in OCI registry.",
            "curl -L https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64 -o /usr/local/bin/cosign && chmod +x /usr/local/bin/cosign",
            "cosign verify {target}",
            "https://github.com/sigstore/cosign",
            "low", &["image"], p_target),
        ("ht_rekor_cli", "rekor_cli", "supply_chain", "transparency",
            "Rekor transparency log CLI for software supply chain.",
            "curl -L https://github.com/sigstore/rekor/releases/latest/download/rekor-cli-linux-amd64 -o /usr/local/bin/rekor-cli && chmod +x /usr/local/bin/rekor-cli",
            "rekor-cli get --log-index 0",
            "https://github.com/sigstore/rekor",
            "low", &["cloud"], p_none),
        ("ht_slsa_verifier", "slsa_verifier", "supply_chain", "provenance",
            "Verify SLSA provenance from artifact builders.",
            "go install github.com/slsa-framework/slsa-verifier/v2/cli/slsa-verifier@latest",
            "slsa-verifier verify-artifact {file}",
            "https://github.com/slsa-framework/slsa-verifier",
            "low", &["file"], p_file),
        ("ht_phylum", "phylum", "supply_chain", "dep_risk",
            "Software supply chain risk analysis tool.",
            "curl -fsSL https://sh.phylum.io | sh",
            "phylum analyze {file}",
            "https://github.com/phylum-dev/cli",
            "low", &["file"], p_file),
        ("ht_socket_cli", "socket", "supply_chain", "dep_risk",
            "Detect supply chain attacks in npm dependencies.",
            "npm install -g socket",
            "socket info {target}",
            "https://github.com/SocketDev/socket-cli",
            "low", &["target"], p_target),
        ("ht_chainguard_apko", "apko", "supply_chain", "image_build",
            "Build OCI images from APK packages declaratively.",
            "curl -L https://github.com/chainguard-dev/apko/releases/latest/download/apko_Linux_x86_64.tar.gz | tar xz -C /usr/local/bin apko",
            "apko build {file} {target} {target}.tar",
            "https://github.com/chainguard-dev/apko",
            "low", &["file"], p_file),
        ("ht_detect_secrets", "detect_secrets", "secrets_scan", "secrets",
            "Detect secrets in code.",
            "pipx install detect-secrets",
            "detect-secrets scan {file}",
            "https://github.com/Yelp/detect-secrets",
            "low", &["file"], p_file),
        ("ht_git_secrets", "git_secrets", "secrets_scan", "secrets",
            "Prevent commits of AWS keys to Git repos.",
            "git clone https://github.com/awslabs/git-secrets && cd git-secrets && sudo make install",
            "git secrets --scan",
            "https://github.com/awslabs/git-secrets",
            "low", &["file"], p_none),
        ("ht_whispers", "whispers", "secrets_scan", "secrets",
            "Identify hardcoded secrets in code/configs.",
            "pipx install whispers",
            "whispers {file}",
            "https://github.com/Skyscanner/whispers",
            "low", &["file"], p_file),
        ("ht_repo_supervisor", "repo_supervisor", "secrets_scan", "secrets",
            "Detect secrets in source code.",
            "npm install -g repo-supervisor",
            "repo-supervisor scan {file}",
            "https://github.com/auth0/repo-supervisor",
            "low", &["file"], p_file),
        ("ht_shhgit", "shhgit", "secrets_scan", "secrets",
            "Find secrets in real time across GitHub/GitLab/Bitbucket.",
            "go install github.com/eth0izzle/shhgit@latest",
            "shhgit --search-query {target}",
            "https://github.com/eth0izzle/shhgit",
            "low", &["target"], p_target),
        ("ht_credsniper", "credsniper", "secrets_scan", "secrets",
            "Modular phishing framework with credential capture.",
            "git clone https://github.com/ustayready/CredSniper && cd CredSniper && pip3 install -r requirements.txt",
            "python3 credsniper.py",
            "https://github.com/ustayready/CredSniper",
            "high", &["url"], p_none),
        ("ht_noseyparker", "noseyparker", "secrets_scan", "secrets",
            "Find secrets and sensitive info in textual data.",
            "curl -L https://github.com/praetorian-inc/noseyparker/releases/latest/download/noseyparker-v0.18.1-x86_64-unknown-linux-gnu.tar.gz | tar xz -C /usr/local/bin",
            "noseyparker scan --datastore /tmp/np {file}",
            "https://github.com/praetorian-inc/noseyparker",
            "low", &["file"], p_file),
        ("ht_akto", "akto", "api_security", "api_test",
            "Open source API security testing platform.",
            "docker pull aktosecurity/akto-api-security-community",
            "docker run -p 9090:9090 aktosecurity/akto-api-security-community",
            "https://github.com/akto-api-security/akto",
            "low", &["url"], p_none),
        ("ht_apinto", "42crunch_audit", "api_security", "api_audit",
            "42Crunch API audit (OpenAPI security analysis).",
            "npm install -g @42crunch/api-security-audit",
            "api-security-audit audit {file}",
            "https://42crunch.com/",
            "low", &["file"], p_file),
        ("ht_postman_newman", "newman", "api_security", "api_test",
            "Command-line collection runner for Postman.",
            "npm install -g newman",
            "newman run {file}",
            "https://github.com/postmanlabs/newman",
            "low", &["file"], p_file),
        ("ht_mayhem_for_api", "mayhem_for_api", "api_security", "fuzzing",
            "Continuous API security testing tool.",
            "curl -L https://app.mayhem.security/cli/Linux/install.sh | bash",
            "mapi run {target}",
            "https://www.mayhem.security/",
            "medium", &["url"], p_url),
        ("ht_apicheck", "apicheck", "api_security", "api_test",
            "API security analysis toolkit.",
            "pipx install apicheck",
            "apicheck scan {url}",
            "https://github.com/BBVA/apicheck",
            "low", &["url"], p_url),
        ("ht_astra_api", "astra", "api_security", "api_test",
            "Automated security testing for REST APIs.",
            "git clone https://github.com/flipkart-incubator/Astra && cd Astra && pip3 install -r requirements.txt",
            "python3 modules/scanner.py -u {url}",
            "https://github.com/flipkart-incubator/Astra",
            "low", &["url"], p_url),
        ("ht_vooki", "vooki", "api_security", "api_test",
            "Free interactive REST API vulnerability scanner.",
            "wget https://github.com/Vooki-Studios/Vooki-REST-API-Scanner/releases/latest/download/Vooki-Linux.tar.gz && tar xf Vooki-Linux.tar.gz",
            "./Vooki/Vooki",
            "https://github.com/Vooki-Studios/Vooki-REST-API-Scanner",
            "low", &["url"], p_url),
        ("ht_graphqlmap", "graphqlmap", "api_security", "graphql",
            "Scripting engine to interact with a GraphQL endpoint.",
            "pip3 install graphqlmap",
            "graphqlmap -u {url}",
            "https://github.com/swisskyrepo/GraphQLmap",
            "medium", &["url"], p_url),
        ("ht_graphql_path_enum", "graphql_path_enum", "api_security", "graphql",
            "GraphQL endpoint path enumerator.",
            "cargo install graphql-path-enum",
            "graphql-path-enum -i schema.json -t Customer",
            "https://github.com/sdnts/graphql-path-enum",
            "low", &["url"], p_none),
        ("ht_inql", "inql", "api_security", "graphql",
            "Burp extension for GraphQL security.",
            "pipx install inql",
            "inql -t {url}",
            "https://github.com/doyensec/inql",
            "low", &["url"], p_url),
        ("ht_clairvoyance", "clairvoyance", "api_security", "graphql",
            "Obtain GraphQL API schema even if introspection is disabled.",
            "pipx install clairvoyance",
            "clairvoyance --url {url}",
            "https://github.com/nikitastupin/clairvoyance",
            "low", &["url"], p_url),
        ("ht_crackql", "crackql", "api_security", "graphql",
            "GraphQL password brute-forcer and fuzzer.",
            "pip3 install crackql",
            "crackql --url {url}",
            "https://github.com/nicholasaleks/CrackQL",
            "medium", &["url"], p_url),
        ("ht_jwt_tool", "jwt_tool", "api_security", "jwt",
            "Toolkit for testing/tweaking/cracking JSON Web Tokens.",
            "git clone https://github.com/ticarpi/jwt_tool && pip3 install -r jwt_tool/requirements.txt",
            "python3 jwt_tool.py {target}",
            "https://github.com/ticarpi/jwt_tool",
            "medium", &["target"], p_target),
        ("ht_socket_io", "wapiti", "web_attack", "dast",
            "Web application vulnerability scanner.",
            "pipx install wapiti3",
            "wapiti -u {url}",
            "https://github.com/wapiti-scanner/wapiti",
            "medium", &["url"], p_url),
        ("ht_w3af", "w3af", "web_attack", "dast",
            "Web Application Attack and Audit Framework.",
            "git clone https://github.com/andresriancho/w3af && cd w3af && ./w3af_console",
            "./w3af_console",
            "https://github.com/andresriancho/w3af",
            "medium", &["url"], p_none),
        ("ht_arachni", "arachni", "web_attack", "dast",
            "Feature-full web application vulnerability scanner framework.",
            "curl -L https://github.com/Arachni/arachni/releases/latest/download/arachni-1.6.1.3-linux-x86_64.tar.gz | tar xz -C /opt",
            "/opt/arachni/bin/arachni {url}",
            "https://github.com/Arachni/arachni",
            "medium", &["url"], p_url),
        ("ht_vulnx", "vulnx", "web_attack", "cms_scan",
            "Intelligent CMS vulnerability scanner.",
            "git clone https://github.com/anouarbensaad/vulnx && pip3 install -r vulnx/requirements.txt",
            "python3 vulnx/vulnx.py -u {url}",
            "https://github.com/anouarbensaad/vulnx",
            "medium", &["url"], p_url),
        ("ht_cmseek", "cmseek", "web_attack", "cms_scan",
            "CMS detection and exploitation suite.",
            "git clone https://github.com/Tuhinshubhra/CMSeeK && pip3 install -r CMSeeK/requirements.txt",
            "python3 CMSeeK/cmseek.py -u {url}",
            "https://github.com/Tuhinshubhra/CMSeeK",
            "medium", &["url"], p_url),
        ("ht_joomscan", "joomscan", "web_attack", "cms_scan",
            "OWASP Joomla! Vulnerability Scanner.",
            "sudo apt install -y joomscan",
            "joomscan --url {url}",
            "https://github.com/OWASP/joomscan",
            "medium", &["url"], p_url),
        ("ht_wpscan", "wpscan", "web_attack", "cms_scan",
            "Black-box WordPress vulnerability scanner.",
            "sudo apt install -y wpscan",
            "wpscan --url {url}",
            "https://github.com/wpscanteam/wpscan",
            "medium", &["url"], p_url),
        ("ht_droopescan", "droopescan", "web_attack", "cms_scan",
            "Plugin-based scanner for Drupal/SilverStripe etc.",
            "pipx install droopescan",
            "droopescan scan -u {url}",
            "https://github.com/droope/droopescan",
            "low", &["url"], p_url),
        ("ht_photon", "photon", "web_attack", "crawler",
            "Incredibly fast crawler for OSINT.",
            "git clone https://github.com/s0md3v/Photon && pip3 install -r Photon/requirements.txt",
            "python3 Photon/photon.py -u {url}",
            "https://github.com/s0md3v/Photon",
            "low", &["url"], p_url),
        ("ht_crlfsuite", "crlfsuite", "web_attack", "crlf",
            "CRLF injection scanner.",
            "pipx install crlfsuite",
            "crlfsuite -u {url}",
            "https://github.com/Nefcore/CRLFsuite",
            "medium", &["url"], p_url),
        ("ht_cspbypass", "cspbypass", "web_attack", "csp",
            "Test CSP bypass with the Google CSP Evaluator.",
            "pipx install csp-bypass",
            "csp-bypass {url}",
            "https://github.com/GoSecure/csp-auditor",
            "low", &["url"], p_url),
        ("ht_byp4xx", "byp4xx", "web_attack", "wafbypass",
            "40x access bypass via header/method/path tricks.",
            "go install github.com/lobuhi/byp4xx@latest",
            "byp4xx {url}",
            "https://github.com/lobuhi/byp4xx",
            "medium", &["url"], p_url),
        ("ht_xnlinkfinder", "xnlinkfinder", "web_attack", "recon",
            "Discover endpoints, parameters, urls and secrets.",
            "pipx install xnLinkFinder",
            "xnLinkFinder -i {url}",
            "https://github.com/xnl-h4ck3r/xnLinkFinder",
            "low", &["url"], p_url),
        ("ht_paramspider", "paramspider", "web_attack", "recon",
            "Mining parameters from web archives for bug hunting.",
            "git clone https://github.com/devanshbatham/paramspider && cd paramspider && pip3 install .",
            "paramspider -d {domain}",
            "https://github.com/devanshbatham/paramspider",
            "low", &["domain"], p_domain),
        ("ht_waybackurls", "waybackurls", "web_attack", "recon",
            "Fetch URLs Wayback Machine knows about for a domain.",
            "go install github.com/tomnomnom/waybackurls@latest",
            "echo {domain} | waybackurls",
            "https://github.com/tomnomnom/waybackurls",
            "low", &["domain"], p_domain),
        ("ht_gau", "gau", "web_attack", "recon",
            "Get All URLs.",
            "go install github.com/lc/gau/v2/cmd/gau@latest",
            "echo {domain} | gau",
            "https://github.com/lc/gau",
            "low", &["domain"], p_domain),
        ("ht_hakrawler", "hakrawler", "web_attack", "crawler",
            "Fast crawler designed for easy quick discovery of endpoints and assets.",
            "go install github.com/hakluke/hakrawler@latest",
            "echo {url} | hakrawler",
            "https://github.com/hakluke/hakrawler",
            "low", &["url"], p_url),
        ("ht_crackmapexec", "crackmapexec", "active_directory", "ad_attack",
            "Swiss army knife for pentesting Windows/AD environments.",
            "pipx install crackmapexec",
            "crackmapexec smb {target}",
            "https://github.com/byt3bl33d3r/CrackMapExec",
            "high", &["target"], p_target),
        ("ht_rubeus", "rubeus", "active_directory", "kerberos",
            "C# toolset for Kerberos abuse.",
            "git clone https://github.com/GhostPack/Rubeus",
            "dotnet build Rubeus/Rubeus.sln && dotnet run -- triage",
            "https://github.com/GhostPack/Rubeus",
            "high", &["target"], p_none),
        ("ht_seatbelt", "seatbelt", "active_directory", "enum",
            "Performs many security oriented host-survey enumerations.",
            "git clone https://github.com/GhostPack/Seatbelt",
            "dotnet build Seatbelt/Seatbelt.sln && dotnet run",
            "https://github.com/GhostPack/Seatbelt",
            "medium", &["host"], p_none),
        ("ht_mimikatz", "mimikatz", "active_directory", "credential_dump",
            "Extract plaintext passwords, hashes, PIN codes from memory.",
            "git clone https://github.com/gentilkiwi/mimikatz",
            "mimikatz.exe",
            "https://github.com/gentilkiwi/mimikatz",
            "critical", &["host"], p_none),
        ("ht_lapsdumper", "lapsdumper", "active_directory", "laps",
            "Dump LAPS passwords from AD.",
            "pipx install lapsdumper",
            "lapsdumper -u {username} -d {domain}",
            "https://github.com/n00py/LAPSDumper",
            "high", &["domain"], p_domain),
        ("ht_promptfoo", "promptfoo", "ai_security", "llm_test",
            "Test prompts, LLMs and RAG pipelines.",
            "npm install -g promptfoo",
            "promptfoo eval",
            "https://github.com/promptfoo/promptfoo",
            "low", &["url"], p_none),
        ("ht_garak", "garak", "ai_security", "llm_redteam",
            "LLM vulnerability scanner.",
            "pipx install garak",
            "garak --model_type huggingface --model_name {target}",
            "https://github.com/leondz/garak",
            "medium", &["target"], p_target),
        ("ht_llm_guard", "llm_guard", "ai_security", "llm_guardrail",
            "Security toolkit for LLM interactions.",
            "pipx install llm-guard",
            "llm-guard --input \"{target}\"",
            "https://github.com/protectai/llm-guard",
            "low", &["target"], p_target),
        ("ht_rebuff", "rebuff", "ai_security", "prompt_injection",
            "Detect prompt injection in real-time.",
            "pip3 install rebuff",
            "python -c \"from rebuff import Rebuff; r=Rebuff(\"x\"); print(r.detect_injection(\"{target}\"))\"",
            "https://github.com/protectai/rebuff",
            "low", &["target"], p_target),
        ("ht_vigil_llm", "vigil_llm", "ai_security", "llm_guardrail",
            "LLM prompt injection and jailbreak detection.",
            "pip3 install vigil-llm",
            "vigil-llm scan --prompt \"{target}\"",
            "https://github.com/deadbits/vigil-llm",
            "low", &["target"], p_target),
        ("ht_plexiglass", "plexiglass", "ai_security", "llm_redteam",
            "Toolkit for LLM red-teaming.",
            "pipx install plexiglass",
            "plexiglass test {target}",
            "https://github.com/safellama/plexiglass",
            "low", &["target"], p_target),
        ("ht_modelscan", "modelscan", "ai_security", "model_scan",
            "Scans ML models for malicious code (pickle, etc).",
            "pipx install modelscan",
            "modelscan -p {file}",
            "https://github.com/protectai/modelscan",
            "low", &["file"], p_file),
        ("ht_counterfit", "counterfit", "ai_security", "adversarial",
            "Generic automation tool for ML model security risk.",
            "git clone https://github.com/Azure/counterfit && cd counterfit && pip3 install .[dev]",
            "python3 -m counterfit",
            "https://github.com/Azure/counterfit",
            "medium", &["target"], p_none),
        ("ht_artpython", "adversarial_robustness_toolbox", "ai_security", "adversarial",
            "IBM ART for adversarial ML attacks/defenses.",
            "pipx install adversarial-robustness-toolbox",
            "python3 -c \"from art import config; print(config.ART_DATA_PATH)\"",
            "https://github.com/Trusted-AI/adversarial-robustness-toolbox",
            "medium", &["file"], p_none),
        ("ht_foolbox", "foolbox", "ai_security", "adversarial",
            "Python toolbox to create adversarial examples.",
            "pip3 install foolbox",
            "python3 -c \"import foolbox; print(foolbox.__version__)\"",
            "https://github.com/bethgelab/foolbox",
            "medium", &["file"], p_none),
        ("ht_giskard", "giskard", "ai_security", "model_test",
            "Open-source AI quality and security testing.",
            "pipx install giskard",
            "giskard scan",
            "https://github.com/Giskard-AI/giskard",
            "low", &["file"], p_none),
        ("ht_aiverify", "aiverify", "ai_security", "model_test",
            "AI testing framework and toolkit (IMDA).",
            "docker pull aiverify/aiverify-portal",
            "docker run -p 3000:3000 aiverify/aiverify-portal",
            "https://github.com/IMDA-BTG/aiverify",
            "low", &["url"], p_none),
        ("ht_rapidfort", "rapidfort", "ai_security", "model_harden",
            "Container/AI model hardening service CLI.",
            "curl -L https://us02.rapidfort.com/cli/rfdownload | bash",
            "rfdownload --image {target}",
            "https://www.rapidfort.com/",
            "low", &["image"], p_target),
        ("ht_aflplusplus", "aflplusplus", "fuzzing", "coverage_fuzzer",
            "American Fuzzy Lop++.",
            "sudo apt install -y afl++",
            "afl-fuzz -i {file} -o /tmp/afl-out -- ./binary @@",
            "https://github.com/AFLplusplus/AFLplusplus",
            "medium", &["file"], p_file),
        ("ht_honggfuzz", "honggfuzz", "fuzzing", "coverage_fuzzer",
            "Security-oriented software fuzzer.",
            "sudo apt install -y honggfuzz",
            "honggfuzz -i {file} -- ./binary",
            "https://github.com/google/honggfuzz",
            "medium", &["file"], p_file),
        ("ht_libfuzzer", "libfuzzer", "fuzzing", "coverage_fuzzer",
            "In-process coverage-guided fuzzer (LLVM).",
            "sudo apt install -y clang",
            "clang -fsanitize=fuzzer {file} -o fuzz && ./fuzz",
            "https://llvm.org/docs/LibFuzzer.html",
            "medium", &["file"], p_file),
        ("ht_boofuzz", "boofuzz", "fuzzing", "protocol_fuzzer",
            "Network protocol fuzzing framework.",
            "pipx install boofuzz",
            "python3 -m boofuzz",
            "https://github.com/jtpereyda/boofuzz",
            "medium", &["target"], p_none),
        ("ht_radamsa", "radamsa", "fuzzing", "grammar_fuzzer",
            "General purpose fuzzer.",
            "sudo apt install -y radamsa",
            "cat {file} | radamsa",
            "https://gitlab.com/akihe/radamsa",
            "low", &["file"], p_file),
        ("ht_peach", "peach", "fuzzing", "protocol_fuzzer",
            "Smart fuzzer for finding software vulnerabilities.",
            "git clone https://github.com/MozillaSecurity/peach && cd peach",
            "./peach -1 {file}",
            "https://github.com/MozillaSecurity/peach",
            "medium", &["file"], p_file),
        ("ht_fuzzdb", "fuzzdb", "fuzzing", "wordlists",
            "Comprehensive open dictionary of fault injection patterns.",
            "git clone https://github.com/fuzzdb-project/fuzzdb",
            "ls fuzzdb/",
            "https://github.com/fuzzdb-project/fuzzdb",
            "low", &["file"], p_none),
        ("ht_misp", "misp", "threat_intel", "sharing",
            "Threat Intelligence Platform — sharing of indicators.",
            "docker pull coolacid/misp-docker:core-latest",
            "docker run -d -p 8443:443 coolacid/misp-docker:core-latest",
            "https://github.com/MISP/MISP",
            "low", &["url"], p_none),
        ("ht_thehive", "thehive", "threat_intel", "soar",
            "SOAR platform for security incident response.",
            "docker pull thehiveproject/thehive4:latest",
            "docker run -d -p 9000:9000 thehiveproject/thehive4",
            "https://github.com/TheHive-Project/TheHive",
            "low", &["url"], p_none),
        ("ht_cortex", "cortex", "threat_intel", "analyzer",
            "Powerful analyzer companion to TheHive.",
            "docker pull thehiveproject/cortex:latest",
            "docker run -d -p 9001:9001 thehiveproject/cortex",
            "https://github.com/TheHive-Project/Cortex",
            "low", &["url"], p_none),
        ("ht_opencti", "opencti", "threat_intel", "platform",
            "Open Cyber Threat Intelligence Platform.",
            "docker pull opencti/platform:latest",
            "docker run -d -p 8080:8080 opencti/platform",
            "https://github.com/OpenCTI-Platform/opencti",
            "low", &["url"], p_none),
        ("ht_yeti", "yeti", "threat_intel", "observable",
            "Curated threat intel through observables/indicators.",
            "docker pull yetiplatform/yeti:latest",
            "docker run -d -p 5000:5000 yetiplatform/yeti",
            "https://github.com/yeti-platform/yeti",
            "low", &["url"], p_none),
        ("ht_intelmq", "intelmq", "threat_intel", "feed",
            "Solution for CERTs to collect and process security feeds.",
            "pipx install intelmq",
            "intelmqctl start",
            "https://github.com/certtools/intelmq",
            "low", &["host"], p_none),
        ("ht_msticpy", "msticpy", "threat_intel", "hunting",
            "Microsoft Threat Intelligence Python Security Tools.",
            "pip3 install msticpy",
            "python3 -c \"import msticpy; print(msticpy.__version__)\"",
            "https://github.com/microsoft/msticpy",
            "low", &["file"], p_none),
        ("ht_jupyterhunter", "jupyter-threat-hunting", "threat_intel", "hunting",
            "Jupyter notebooks for threat hunting.",
            "git clone https://github.com/cyb3rward0g/notebooks-forensics",
            "jupyter notebook",
            "https://github.com/Cyb3rWard0g/HELK",
            "low", &["file"], p_none),
        ("ht_sigma", "sigma", "threat_intel", "detection",
            "Generic signature format for SIEM systems.",
            "pipx install sigma-cli",
            "sigma convert {file}",
            "https://github.com/SigmaHQ/sigma",
            "low", &["file"], p_file),
        ("ht_chainsaw", "chainsaw", "threat_intel", "windows_log",
            "Hunt through Windows event logs.",
            "curl -L https://github.com/WithSecureLabs/chainsaw/releases/latest/download/chainsaw_x86_64-unknown-linux-gnu.tar.gz | tar xz -C /usr/local/bin",
            "chainsaw hunt {file}",
            "https://github.com/WithSecureLabs/chainsaw",
            "low", &["file"], p_file),
        ("ht_hayabusa", "hayabusa", "threat_intel", "windows_log",
            "Sigma-based windows event log fast forensics timeline generator.",
            "curl -L https://github.com/Yamato-Security/hayabusa/releases/latest/download/hayabusa-2.16.0-linux.zip -o /tmp/hb.zip && unzip /tmp/hb.zip -d /opt/hayabusa",
            "/opt/hayabusa/hayabusa csv-timeline -d {file}",
            "https://github.com/Yamato-Security/hayabusa",
            "low", &["file"], p_file),
        ("ht_velociraptor", "velociraptor", "threat_intel", "dfir",
            "Advanced digital forensic and incident response tool.",
            "curl -L https://github.com/Velocidex/velociraptor/releases/latest/download/velociraptor-v0.7.1-linux-amd64 -o /usr/local/bin/velociraptor && chmod +x /usr/local/bin/velociraptor",
            "velociraptor gui",
            "https://github.com/Velocidex/velociraptor",
            "low", &["host"], p_none),
        ("ht_osquery", "osquery", "threat_intel", "endpoint",
            "SQL-powered operating system instrumentation.",
            "sudo apt install -y osquery",
            "osqueryi \"SELECT * FROM users;\"",
            "https://github.com/osquery/osquery",
            "low", &["host"], p_none),
        ("ht_grr", "grr", "threat_intel", "dfir",
            "Live remote forensics framework.",
            "docker pull grrdocker/grr",
            "docker run -d -p 8000:8000 grrdocker/grr",
            "https://github.com/google/grr",
            "low", &["host"], p_none),
        ("ht_cuckoo", "cuckoo", "malware_analysis", "sandbox",
            "Automated malware analysis sandbox.",
            "pipx install cuckoo",
            "cuckoo",
            "https://github.com/cuckoosandbox/cuckoo",
            "medium", &["file"], p_none),
        ("ht_cape", "cape", "malware_analysis", "sandbox",
            "Configuration And Payload Extraction sandbox.",
            "git clone https://github.com/kevoreilly/CAPEv2",
            "python3 cape.py",
            "https://github.com/kevoreilly/CAPEv2",
            "medium", &["file"], p_none),
        ("ht_die", "detect_it_easy", "malware_analysis", "file_id",
            "Identify packers, compilers, protectors.",
            "sudo apt install -y detect-it-easy",
            "die {file}",
            "https://github.com/horsicq/Detect-It-Easy",
            "low", &["file"], p_file),
        ("ht_upx", "upx", "malware_analysis", "packer",
            "Ultimate packer for executables.",
            "sudo apt install -y upx",
            "upx -d {file}",
            "https://github.com/upx/upx",
            "low", &["file"], p_file),
        ("ht_yara", "yara", "malware_analysis", "rule_engine",
            "Pattern matching swiss-army knife for malware research.",
            "sudo apt install -y yara",
            "yara {file} {target}",
            "https://github.com/VirusTotal/yara",
            "low", &["file"], p_file),
        ("ht_yextend", "yextend", "malware_analysis", "yara_archive",
            "Yara helper that extends matching to archives/scripts.",
            "git clone https://github.com/BayshoreNetworks/yextend",
            "./yextend/yextend -r {file} -t {target}",
            "https://github.com/BayshoreNetworks/yextend",
            "low", &["file"], p_file),
        ("ht_capa", "capa", "malware_analysis", "behavior",
            "Identify capabilities in executable files.",
            "pipx install flare-capa",
            "capa {file}",
            "https://github.com/mandiant/capa",
            "low", &["file"], p_file),
        ("ht_floss", "floss", "malware_analysis", "strings",
            "Mandiant FLARE Obfuscated String Solver.",
            "pipx install flare-floss",
            "floss {file}",
            "https://github.com/mandiant/flare-floss",
            "low", &["file"], p_file),
        ("ht_pestudio", "pestudio", "malware_analysis", "pe_inspect",
            "Initial malware analysis of Windows executables.",
            "wget https://www.winitor.com/tools/pestudio/current/pestudio.zip",
            "./pestudio/pestudio.exe",
            "https://www.winitor.com/",
            "low", &["file"], p_none),
        ("ht_pe_tree", "pe_tree", "malware_analysis", "pe_inspect",
            "Tree-view PE file inspector.",
            "pipx install pe-tree",
            "pe-tree {file}",
            "https://github.com/blackberry/pe_tree",
            "low", &["file"], p_file),
        ("ht_peframe", "peframe", "malware_analysis", "pe_inspect",
            "Static analysis of PE/ELF files.",
            "pipx install peframe",
            "peframe {file}",
            "https://github.com/guelfoweb/peframe",
            "low", &["file"], p_file),
        ("ht_viper", "viper", "malware_analysis", "framework",
            "Binary analysis and management framework.",
            "pipx install viper-framework",
            "viper",
            "https://github.com/viper-framework/viper",
            "low", &["file"], p_none),
        ("ht_intezer_analyze", "intezer_analyze_cli", "malware_analysis", "genetic",
            "Genetic malware analysis service CLI.",
            "pipx install intezer-analyze-cli",
            "intezer-analyze analyze {file}",
            "https://github.com/intezer/analyze-cli",
            "low", &["file"], p_file),
        ("ht_slither", "slither", "web3_security", "solidity_static",
            "Solidity static analysis framework.",
            "pipx install slither-analyzer",
            "slither {file}",
            "https://github.com/crytic/slither",
            "low", &["file"], p_file),
        ("ht_mythril", "mythril", "web3_security", "solidity_sym",
            "Security analysis tool for EVM bytecode.",
            "pipx install mythril",
            "myth analyze {file}",
            "https://github.com/Consensys/mythril",
            "low", &["file"], p_file),
        ("ht_manticore", "manticore", "web3_security", "symbolic",
            "Symbolic execution tool for analysis of binaries and smart contracts.",
            "pipx install manticore",
            "manticore {file}",
            "https://github.com/trailofbits/manticore",
            "low", &["file"], p_file),
        ("ht_echidna", "echidna", "web3_security", "fuzzer",
            "Fast smart contract fuzzer.",
            "docker pull trailofbits/echidna",
            "docker run -v $PWD:/src trailofbits/echidna echidna-test /src/{file}",
            "https://github.com/crytic/echidna",
            "low", &["file"], p_file),
        ("ht_crytic_compile", "crytic_compile", "web3_security", "build",
            "Abstraction layer for compiling Solidity.",
            "pipx install crytic-compile",
            "crytic-compile {file}",
            "https://github.com/crytic/crytic-compile",
            "low", &["file"], p_file),
        ("ht_certora_prover", "certora_prover", "web3_security", "formal",
            "Formal verification of smart contracts.",
            "pip3 install certora-cli",
            "certoraRun {file}",
            "https://github.com/Certora/CertoraProver",
            "low", &["file"], p_file),
        ("ht_foundry_forge", "foundry", "web3_security", "test_suite",
            "Smart contract testing framework (forge).",
            "curl -L https://foundry.paradigm.xyz | bash && foundryup",
            "forge test",
            "https://github.com/foundry-rs/foundry",
            "low", &["file"], p_none),
        ("ht_semgrep_solidity", "semgrep_solidity", "web3_security", "solidity_static",
            "Semgrep rules for Solidity smart contracts.",
            "pipx install semgrep",
            "semgrep --config p/solidity {file}",
            "https://github.com/Decurity/semgrep-smart-contracts",
            "low", &["file"], p_file),
        ("ht_drozer", "drozer", "mobile_modern", "android",
            "Comprehensive security and attack framework for Android.",
            "pip3 install drozer",
            "drozer console connect",
            "https://github.com/WithSecureLabs/drozer",
            "high", &["apk"], p_apk),
        ("ht_apkx", "apkx", "mobile_modern", "android",
            "Multi-purpose APK decompiler.",
            "pipx install apkx",
            "apkx {apk}",
            "https://github.com/b-mueller/apkx",
            "low", &["apk"], p_apk),
        ("ht_apktool", "apktool", "mobile_modern", "android",
            "Tool for reverse engineering Android apk files.",
            "sudo apt install -y apktool",
            "apktool d {apk}",
            "https://github.com/iBotPeaches/Apktool",
            "low", &["apk"], p_apk),
        ("ht_quark_engine", "quark_engine", "mobile_modern", "android",
            "Android malware (analysis & scoring) system.",
            "pipx install quark-engine",
            "quark -a {apk}",
            "https://github.com/quark-engine/quark-engine",
            "low", &["apk"], p_apk),
        ("ht_androbugs", "androbugs", "mobile_modern", "android",
            "Android vulnerability analysis system.",
            "git clone https://github.com/AndroBugs/AndroBugs_Framework",
            "python3 AndroBugs_Framework/androbugs.py -f {apk}",
            "https://github.com/AndroBugs/AndroBugs_Framework",
            "low", &["apk"], p_apk),
        ("ht_androwarn", "androwarn", "mobile_modern", "android",
            "Static analyzer that detects malicious behaviors in Android apps.",
            "pipx install androwarn",
            "androwarn -i {apk} -r html",
            "https://github.com/maaaaz/androwarn",
            "low", &["apk"], p_apk),
        ("ht_iblessing", "iblessing", "mobile_modern", "ios",
            "iOS security exploiting toolkit.",
            "brew install ws1986/iblessing/iblessing",
            "iblessing -m apple-info -p {file}",
            "https://github.com/Soulghost/iblessing",
            "medium", &["file"], p_file),
        ("ht_passionfruit", "passionfruit", "mobile_modern", "ios",
            "Simple iOS app blackbox assessment tool with frida.",
            "npm install -g passionfruit",
            "passionfruit",
            "https://github.com/chaitin/passionfruit",
            "medium", &["file"], p_none),
        ("ht_grapefruit", "grapefruit", "mobile_modern", "ios",
            "Runtime application instruments for iOS.",
            "npm install -g igrapefruit",
            "igrapefruit",
            "https://github.com/ChiChou/grapefruit",
            "medium", &["file"], p_none),
        ("ht_idb", "idb", "mobile_modern", "ios",
            "iOS Debug Bridge for app testing.",
            "pipx install idb",
            "idb shell",
            "https://github.com/dmayer/idb",
            "medium", &["file"], p_none),
        ("ht_ggshield", "ggshield", "ci_cd_security", "secret_scan",
            "GitGuardian CLI to detect 350+ types of secrets.",
            "pipx install ggshield",
            "ggshield secret scan path {file}",
            "https://github.com/GitGuardian/ggshield",
            "low", &["file"], p_file),
        ("ht_semgrep_supplychain", "semgrep_supplychain", "ci_cd_security", "supply_chain",
            "Semgrep Supply Chain CLI.",
            "pipx install semgrep",
            "semgrep ci --supply-chain",
            "https://semgrep.dev/products/supply-chain/",
            "low", &["file"], p_none),
        ("ht_legitify", "legitify", "ci_cd_security", "scm_audit",
            "Detect and remediate SCM misconfigurations.",
            "go install github.com/Legit-Labs/legitify@latest",
            "legitify analyze --org {target}",
            "https://github.com/Legit-Labs/legitify",
            "low", &["target"], p_target),
        ("ht_octoscan", "octoscan", "ci_cd_security", "gha_audit",
            "Static security scanner for GitHub Actions workflows.",
            "go install github.com/synacktiv/octoscan@latest",
            "octoscan scan {file}",
            "https://github.com/synacktiv/octoscan",
            "low", &["file"], p_file),
        ("ht_zizmor", "zizmor", "ci_cd_security", "gha_audit",
            "Static analysis for GitHub Actions security.",
            "pipx install zizmor",
            "zizmor {file}",
            "https://github.com/woodruffw/zizmor",
            "low", &["file"], p_file),
        ("ht_chainbench", "chain_bench", "ci_cd_security", "sscs",
            "Auditing your CI/CD systems against CIS Benchmarks.",
            "curl -L https://github.com/aquasecurity/chain-bench/releases/latest/download/chain-bench_Linux_x86_64.tar.gz | tar xz -C /usr/local/bin chain-bench",
            "chain-bench scan -r {target}",
            "https://github.com/aquasecurity/chain-bench",
            "low", &["target"], p_target),
        ("ht_artifactory_audit", "artifactory_audit", "ci_cd_security", "registry",
            "JFrog Artifactory security audit script.",
            "pipx install jfrog-cli-py",
            "jf rt search \"*\"",
            "https://jfrog.com/help/r/jfrog-cli/",
            "low", &["url"], p_none),
        ("ht_trivy_repo", "trivy_repo", "ci_cd_security", "repo_scan",
            "Trivy git repo scan for vulnerabilities and secrets.",
            "curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin",
            "trivy repo {url}",
            "https://github.com/aquasecurity/trivy",
            "low", &["url"], p_url),
        ("ht_grype_dir", "grype_dir", "ci_cd_security", "sbom_scan",
            "Grype directory and SBOM scanning.",
            "curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin",
            "grype dir:{file}",
            "https://github.com/anchore/grype",
            "low", &["file"], p_file),
        ("ht_chaos", "chaos", "information_gathering", "subdomain",
            "ProjectDiscovery chaos client for subdomain dataset.",
            "go install github.com/projectdiscovery/chaos-client/cmd/chaos@latest",
            "chaos -d {domain}",
            "https://github.com/projectdiscovery/chaos-client",
            "low", &["domain"], p_domain),
        ("ht_shuffledns", "shuffledns", "information_gathering", "subdomain",
            "MassDNS wrapper for active subdomain bruteforcing.",
            "go install github.com/projectdiscovery/shuffledns/cmd/shuffledns@latest",
            "shuffledns -d {domain} -w {wordlist} -r resolvers.txt",
            "https://github.com/projectdiscovery/shuffledns",
            "low", &["domain"], p_domain),
        ("ht_puredns", "puredns", "information_gathering", "subdomain",
            "Fast domain resolver and subdomain bruteforcing tool.",
            "go install github.com/d3mondev/puredns/v2@latest",
            "puredns bruteforce {wordlist} {domain}",
            "https://github.com/d3mondev/puredns",
            "low", &["domain"], p_domain),
        ("ht_dnsx", "dnsx", "information_gathering", "dns",
            "Fast and multi-purpose DNS toolkit.",
            "go install github.com/projectdiscovery/dnsx/cmd/dnsx@latest",
            "echo {domain} | dnsx -a -resp",
            "https://github.com/projectdiscovery/dnsx",
            "low", &["domain"], p_domain),
        ("ht_mapcidr", "mapcidr", "information_gathering", "ip_ops",
            "Utility for performing multiple operations for a given CIDR.",
            "go install github.com/projectdiscovery/mapcidr/cmd/mapcidr@latest",
            "mapcidr -cidr {target}",
            "https://github.com/projectdiscovery/mapcidr",
            "low", &["target"], p_target),
        ("ht_asnmap", "asnmap", "information_gathering", "asn",
            "Quickly map any organization's network ranges using ASN information.",
            "go install github.com/projectdiscovery/asnmap/cmd/asnmap@latest",
            "asnmap -d {domain}",
            "https://github.com/projectdiscovery/asnmap",
            "low", &["domain"], p_domain),
        ("ht_cdncheck", "cdncheck", "information_gathering", "cdn",
            "Detect tech behind given URLs (CDN, WAF, cloud).",
            "go install github.com/projectdiscovery/cdncheck/cmd/cdncheck@latest",
            "echo {domain} | cdncheck",
            "https://github.com/projectdiscovery/cdncheck",
            "low", &["domain"], p_domain),
        ("ht_tlsx", "tlsx", "information_gathering", "tls_scan",
            "Fast and configurable TLS grabber.",
            "go install github.com/projectdiscovery/tlsx/cmd/tlsx@latest",
            "echo {domain} | tlsx",
            "https://github.com/projectdiscovery/tlsx",
            "low", &["domain"], p_domain),
        ("ht_uncover", "uncover", "information_gathering", "asset_discovery",
            "Quickly discover exposed hosts on the internet via Shodan/Censys/Fofa.",
            "go install github.com/projectdiscovery/uncover/cmd/uncover@latest",
            "uncover -q \"{target}\"",
            "https://github.com/projectdiscovery/uncover",
            "low", &["target"], p_target),
        ("ht_interactsh", "interactsh", "information_gathering", "oast",
            "Out-of-band interaction gathering server and CLI.",
            "go install github.com/projectdiscovery/interactsh/cmd/interactsh-client@latest",
            "interactsh-client",
            "https://github.com/projectdiscovery/interactsh",
            "low", &["url"], p_none),
        ("ht_notify", "notify", "information_gathering", "alerting",
            "Stream the output of several tools to multiple platforms.",
            "go install github.com/projectdiscovery/notify/cmd/notify@latest",
            "echo \"alert\" | notify",
            "https://github.com/projectdiscovery/notify",
            "low", &["url"], p_none),
        ("ht_proxify", "proxify", "web_attack", "proxy",
            "Swiss army knife proxy tool for HTTP/HTTPS traffic capture.",
            "go install github.com/projectdiscovery/proxify/cmd/proxify@latest",
            "proxify",
            "https://github.com/projectdiscovery/proxify",
            "low", &["url"], p_none),
        ("ht_cvemap", "cvemap", "information_gathering", "cve",
            "Navigate the CVE jungle with ease using cvemap.",
            "go install github.com/projectdiscovery/cvemap/cmd/cvemap@latest",
            "cvemap -id {target}",
            "https://github.com/projectdiscovery/cvemap",
            "low", &["target"], p_target),
        ("ht_aix", "aix", "information_gathering", "ai_recon",
            "LLM-powered recon assistant.",
            "go install github.com/projectdiscovery/aix/cmd/aix@latest",
            "aix \"find subs of {domain}\"",
            "https://github.com/projectdiscovery/aix",
            "low", &["domain"], p_domain),
        ("ht_osmedeus", "osmedeus", "information_gathering", "workflow",
            "Fully automated offensive security framework.",
            "curl -fsSL https://raw.githubusercontent.com/j3ssie/osmedeus/master/install.sh | bash",
            "osmedeus scan -t {target}",
            "https://github.com/j3ssie/osmedeus",
            "medium", &["target"], p_target),
        ("ht_reconftw", "reconftw", "information_gathering", "workflow",
            "Powerful recon script for bug bounty.",
            "git clone https://github.com/six2dez/reconftw && cd reconftw && bash install.sh",
            "reconftw -d {domain} -r",
            "https://github.com/six2dez/reconftw",
            "medium", &["domain"], p_domain),
        ("ht_axiom", "axiom", "information_gathering", "infra",
            "Dynamic infrastructure framework for fan-out scanning.",
            "bash <(curl -s https://raw.githubusercontent.com/pry0cc/axiom/master/interact/axiom-configure)",
            "axiom-init test",
            "https://github.com/pry0cc/axiom",
            "low", &["cloud"], p_none),
        ("ht_interlace", "interlace", "information_gathering", "parallel",
            "Easily turn single-threaded CLI apps into a fast parallel app.",
            "pipx install interlace",
            "interlace -tL {file} -threads 5 -c \"command\"",
            "https://github.com/codingo/Interlace",
            "low", &["file"], p_file),
        ("ht_hostilizer", "hostilizer", "information_gathering", "brute",
            "Wordlist generator for security tools.",
            "pipx install hostilizer",
            "hostilizer --domain {domain}",
            "https://github.com/0xJin/hostilizer",
            "low", &["domain"], p_domain),
        ("ht_shosubgo", "shosubgo", "information_gathering", "subdomain",
            "Small Go tool to grab subdomains using Shodan API.",
            "go install github.com/incogbyte/shosubgo@latest",
            "shosubgo -d {domain} -s SHODAN_API_KEY",
            "https://github.com/incogbyte/shosubgo",
            "low", &["domain"], p_domain),
        ("ht_crtsh", "crtsh", "information_gathering", "subdomain",
            "Pull subdomain info from crt.sh.",
            "pip3 install crtsh",
            "crtsh {domain}",
            "https://github.com/PaulSec/crt.sh",
            "low", &["domain"], p_domain),
        ("ht_certgraph", "certgraph", "information_gathering", "tls",
            "Crawl tls trust graph.",
            "go install github.com/lanrat/certgraph@latest",
            "certgraph {domain}",
            "https://github.com/lanrat/certgraph",
            "low", &["domain"], p_domain),
        ("ht_massdns", "massdns", "information_gathering", "dns",
            "High-performance DNS stub resolver.",
            "sudo apt install -y massdns",
            "massdns -r resolvers.txt -t A {file}",
            "https://github.com/blechschmidt/massdns",
            "low", &["file"], p_file),
        ("ht_bbot", "bbot", "information_gathering", "recon",
            "Multipurpose recon framework.",
            "pipx install bbot",
            "bbot -t {target} -f subdomain-enum",
            "https://github.com/blacklanternsecurity/bbot",
            "low", &["target"], p_target),
        ("ht_one_for_all", "oneforall", "information_gathering", "subdomain",
            "OneForAll subdomain enumeration tool.",
            "git clone https://github.com/shmilylty/OneForAll && cd OneForAll && pip3 install -r requirements.txt",
            "python3 oneforall.py --target {domain} run",
            "https://github.com/shmilylty/OneForAll",
            "low", &["domain"], p_domain),
        ("ht_crawlergo", "crawlergo", "information_gathering", "crawler",
            "Powerful browser crawler for web vulnerability scanners.",
            "curl -L https://github.com/Qianlitp/crawlergo/releases/latest/download/crawlergo_linux_amd64 -o /usr/local/bin/crawlergo && chmod +x /usr/local/bin/crawlergo",
            "crawlergo -c chrome -t 10 {url}",
            "https://github.com/Qianlitp/crawlergo",
            "low", &["url"], p_url),
        ("ht_rad_crawler", "rad", "information_gathering", "crawler",
            "A web crawler designed for vulnerability scanners.",
            "curl -L https://github.com/chaitin/rad/releases/latest/download/rad_linux_amd64.zip -o /tmp/rad.zip && unzip /tmp/rad.zip -d /usr/local/bin",
            "rad -t {url}",
            "https://github.com/chaitin/rad",
            "low", &["url"], p_url),
        ("ht_sn1per", "sn1per", "information_gathering", "workflow",
            "Automated pentest framework.",
            "git clone https://github.com/1N3/Sn1per && cd Sn1per && sudo bash install.sh",
            "sn1per --target {target}",
            "https://github.com/1N3/Sn1per",
            "medium", &["target"], p_target),
        ("ht_vajra", "vajra", "information_gathering", "workflow",
            "UI-based offensive framework that aids in recon and exploitation.",
            "git clone https://github.com/r3curs1v3-pr0xy/vajra && cd vajra && pip3 install -r requirements.txt",
            "python3 manage.py runserver",
            "https://github.com/r3curs1v3-pr0xy/vajra",
            "medium", &["target"], p_none),
        ("ht_lazyrecon", "lazyrecon", "information_gathering", "workflow",
            "Subdomain discovery, vuln scanning, dir brute.",
            "git clone https://github.com/nahamsec/lazyrecon",
            "bash lazyrecon/lazyrecon.sh -d {domain}",
            "https://github.com/nahamsec/lazyrecon",
            "medium", &["domain"], p_domain),
        ("ht_nemesis", "nemesis", "information_gathering", "recon",
            "Offensive data enrichment platform.",
            "docker pull specterops/nemesis",
            "docker run -d -p 8000:8000 specterops/nemesis",
            "https://github.com/SpecterOps/Nemesis",
            "medium", &["target"], p_none),
    ]
}

/// Upsert all modern tool entries into the `tools` table. Same logic as
/// hackingtool_seed::seed_hackingtools but for the modern catalog.
pub async fn seed_modern_tools(pool: &PgPool) -> Result<(usize, usize), sqlx::Error> {
    let entries = catalog_modern();
    let mut inserted = 0usize;
    let mut updated = 0usize;
    for (id, name, biz_cat, sub, desc, install, cmd, url, danger, target_types, params_fn) in &entries {
        let params = params_fn();
        let danger_text = match *danger {
            "low"      => "Low risk — read-only or self-contained.",
            "medium"   => "Medium risk — may produce noisy traffic.",
            "high"     => "High risk — actively exploits or modifies targets.",
            "critical" => "Critical — destructive / weaponizable. Authorization required.",
            _          => "Unknown risk.",
        };
        let target_types_json = serde_json::to_value(target_types).unwrap_or(json!([]));
        let merged_params = json!({
            "form": params.get("form").cloned().unwrap_or(json!([])),
            "danger_level": danger,
            "target_types": target_types_json,
        });
        let res: (bool,) = sqlx::query_as(
            r#"
            INSERT INTO tools (
                id, name, category, description, command_template, parameters,
                plan_required, is_active, tool_type, install_command, official_url,
                business_name, business_description, business_category, subcategory,
                risk_context, tool_group, binary_name, kali_package
            ) VALUES (
                $1, $2, 'hackingtool', $3, $4, $5,
                'starter', FALSE, 'cli', $6, $7,
                $2, $3, $8, $9,
                $10, 'hackingtool', $2, ''
            )
            ON CONFLICT (id) DO UPDATE SET
                name = EXCLUDED.name,
                description = EXCLUDED.description,
                command_template = EXCLUDED.command_template,
                parameters = EXCLUDED.parameters,
                install_command = EXCLUDED.install_command,
                official_url = EXCLUDED.official_url,
                business_name = EXCLUDED.business_name,
                business_description = EXCLUDED.business_description,
                business_category = EXCLUDED.business_category,
                subcategory = EXCLUDED.subcategory,
                risk_context = EXCLUDED.risk_context,
                tool_group = EXCLUDED.tool_group
                -- NB: deliberately NOT touching is_active on conflict so that
                -- operator-initiated deactivations (e.g. scripts/tool_smoke_test.py)
                -- survive subsequent seeder runs.
            RETURNING (xmax = 0)
            "#,
        )
        .bind(id).bind(name).bind(desc).bind(cmd).bind(&merged_params)
        .bind(install).bind(url).bind(biz_cat).bind(sub).bind(danger_text)
        .fetch_one(pool).await?;
        if res.0 { inserted += 1; } else { updated += 1; }
    }
    Ok((inserted, updated))
}
